# Generated by Django 3.1.2 on 2020-10-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0002_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='maintenance',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
