# Generated by Django 3.1.2 on 2020-10-23 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_system', '0001_initial'),
        ('user_system', '0004_account_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='maintenance',
        ),
        migrations.AlterField(
            model_name='account',
            name='district',
            field=models.ForeignKey(null=True, on_delete=models.SET(None), to='location_system.district'),
        ),
    ]
