# Generated by Django 3.1.2 on 2020-10-31 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_system', '0005_auto_20201023_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total', models.FloatField(default=0)),
                ('balance', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'bills',
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_date', models.DateField()),
                ('state', models.BooleanField(default=0)),
                ('mount', models.FloatField(default=0)),
                ('delivery', models.FloatField(default=0)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_system.bill')),
            ],
            options={
                'db_table': 'operations',
            },
        ),
        migrations.CreateModel(
            name='OperationProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_id', to='shop_system.operation')),
            ],
            options={
                'db_table': 'operations_products',
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('time', models.IntegerField()),
                ('type', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'rates',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('unit_cost', models.FloatField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_system.account')),
                ('operations', models.ManyToManyField(related_name='products', through='shop_system.OperationProduct', to='shop_system.Operation')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.AddField(
            model_name='operationproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_id', to='shop_system.product'),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('dni', models.CharField(max_length=11)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=90)),
                ('credit_total', models.FloatField(default=0)),
                ('credit_balance', models.FloatField(default=0)),
                ('rate_value', models.FloatField()),
                ('quotation', models.IntegerField(default=1)),
                ('billing_closing', models.DateField()),
                ('payday', models.DateField()),
                ('maintenance', models.FloatField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_system.account')),
                ('rate', models.ForeignKey(null=True, on_delete=models.SET(None), to='shop_system.rate')),
            ],
            options={
                'db_table': 'clients',
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_system.client'),
        ),
    ]
