# Generated by Django 3.1.3 on 2020-11-20 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_system', '0006_auto_20201103_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('dni', models.CharField(max_length=11)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=90)),
                ('credit_total', models.FloatField(default=0)),
                ('compensatory_value', models.FloatField()),
                ('moratorium_value', models.FloatField(default=0)),
                ('quotation', models.IntegerField(default=1)),
                ('open_date', models.DateField(null=True)),
                ('maintenance', models.FloatField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_system.account')),
            ],
            options={
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_date', models.DateField(unique=True)),
                ('state', models.BooleanField(default=False)),
                ('delivery', models.FloatField(default=0)),
                ('maintenance', models.FloatField(default=0)),
                ('balance', models.FloatField(default=0)),
                ('pay_date', models.DateField(null=True)),
                ('time', models.IntegerField(default=30)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_system.client')),
            ],
            options={
                'db_table': 'operations',
            },
        ),
        migrations.CreateModel(
            name='OperationProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_id', to='shop_system.operation')),
            ],
            options={
                'db_table': 'operations_products',
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('time', models.IntegerField()),
                ('type', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'rates',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('unit_cost', models.FloatField()),
                ('measurement', models.CharField(max_length=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_system.account')),
                ('operations', models.ManyToManyField(related_name='products', through='shop_system.OperationProduct', to='shop_system.Operation')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.AddField(
            model_name='operationproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_id', to='shop_system.product'),
        ),
        migrations.AddField(
            model_name='client',
            name='rate',
            field=models.ForeignKey(null=True, on_delete=models.SET(None), to='shop_system.rate'),
        ),
    ]
