# Generated by Django 3.1.2 on 2020-11-03 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='total',
        ),
        migrations.RemoveField(
            model_name='client',
            name='credit_balance',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='mount',
        ),
    ]
