# Generated by Django 3.1.2 on 2020-10-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='type',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
