# Generated by Django 3.1.2 on 2020-11-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_system', '0002_auto_20201103_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='close',
            field=models.BooleanField(default=False),
        ),
    ]
