# Generated by Django 3.1.2 on 2020-11-04 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_system', '0003_operation_close'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='measurement',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
