# Generated by Django 3.1.3 on 2020-11-22 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_system', '0003_auto_20201120_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='currency',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
    ]
